### ISSUE TITLE
Automatic cell saving

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/SpreadSheetTool#17]
As a user who wants to edit an existing SqueakSheet, I don't want to have to press Ctrl+s every time in order to make the yellow triangle disappear.

Acceptance criteria:
- [ ] The yellow triangle no longer appears when text in a cell is edited
- [ ] The text in the cell is still persisted

**Comment by LinqLover** [comment]
Estimated effort: 3

**Comment by georgt99** [comment]
MAJOR BUG: text is only saved automatically when adding symbols. Removing symbols will not automatically save and manually saving will even revert to when you last added a symbol.
(Shortening text is only possible by removing one more symbol than you wanted to and then retyping that symbol. Removing all content is impossible.)

**Comment by LinqLover** [comment]
This is a known bug from Squeak-5.2. You might want to install the latest Trunk update to solve the problem. In Jannis' and mine estimation, it is a bug in the widget implementation before a recent Trunk update itself.

We should discuss whether it would be appropriate to deliver a framework fix with our tool.

(Btw, could you open a new issue for bug reports next time rather than commenting a closed issue? :) )
________________________________

**Comment by LinqLover** [comment]
@MrModder Is it okay to check off the two criteria above?
