### ISSUE TITLE
Simple formulas

### ISSUE THREAD

**Issue by LeonMatthes** [hpi-swa-teaching/SpreadSheetTool#25]
As a smalltalk-programmer I want to be able to enter Smalltalk code into a cell and have it be calculated, in order to have an easy way to organize my calculations.

Acceptance criteria:
- [x] When I enter a text in the cell that starts with  "^" and save it, the cells contents are evaluated as a Smalltalk expression
- [x] When such a cell looses keyboard focus, it displays the result of the calculation
- [x] When such a cell regains keyboard focus it again displays the smalltalk formula

**Comment by LeonMatthes** [comment]
Also see information in #4

**Comment by LinqLover** [comment]
As a Squeak user & dev, I would prefer the following behavior:

- Each cell's value is saved automatically, unless it contains a formula (starts with a `^`)
- For each formula cell:
  - When FC is saved, it displays the result of the calculation
  - When FC shows the result of the calculation and it is sent any input event (some key pressed, including Enter/Ctrl + S), it displays the underlying formula (the last typed character will be discarded)
  - When FC looses keyboard focus, it only displays the result of the calculation if there are no unsaved changes. Otherwise, it keeps displaying the unsaved formula
  - When FC regains keyboard focus, if displays the Smalltalk formula.

Also, I would greatly appreciate color codes indicating the edit mode of a cell (issue coming soon).

**Comment by LinqLover** [comment]
As discussed in meeting:

- [x] When I enter a text in the cell that starts with `^` and save it, the cell's contents are evaluated as a Smalltalk expression
- [x] When such a cell looses keyboard focus, it is not automatically saved
- [x] When I accept the formula cell (by pressing Enter), the formula is recomputed
- [x] When a FC looses focus and has no unsaved changes, it displays the old computed value

@MrModder Would this meet your expectations?
